codecov:
  require_ci_to_pass: yes
ignore:
  - src/precompile.jl
coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      source:
        paths:
          - "src/"
        target: 95%
        threshold: 0.1
    patch:
      default:
        target: 90%  # new contributions should have a coverage at least equal to target